In [1]:
import pandas as pd
import os
from tqdm import tqdm
import matplotlib.pyplot as plt
import plotly.express as px

import xml.etree.ElementTree as ET
from sklearn.preprocessing import MinMaxScaler

### Data

In [2]:
hpv_positive_genes = pd.read_csv('Results/SOM results/HPV positive top genes.csv')
hpv_negative_genes = pd.read_csv('Results/SOM results/HPV negative top genes.csv')

hpv_pos_som_top_direct = pd.read_csv('Results/SOM results/hpv_positive_som_top_direct_drug_candidates_agg.csv')
hpv_neg_som_top_direct = pd.read_csv('Results/SOM results/hpv_negative_som_top_direct_drug_candidates_agg.csv')

hpv_pos_som_top_indirect = pd.read_csv('Results/SOM results/hpv_positive_som_top_indirect_drug_candidates_agg.csv')
hpv_neg_som_top_indirect = pd.read_csv('Results/SOM results/hpv_negative_som_top_indirect_drug_candidates_agg.csv')

### HPV+

In [3]:
hpv_positive_genes

,Gene,Count,Cohort_Frequency,Normalized_Count,Normalized_Cohort_Frequency,P_Value,Adjusted_P_Value,Significant,Empirical_P_Value,Adjusted_Empirical_P_Value,frequency_percentage,mutation_score
0,PIK3CA,18,17,0.002182,0.002061,1.055322e-21,4.630755e-18,True,0.0,0.0,23.611111,0.051515
1,ZNF750,11,8,0.003502,0.002547,4.795352e-16,1.052100e-12,True,0.0,0.0,11.111111,0.038912
2,CCDC191,6,6,0.001148,0.001148,1.514273e-06,1.107438e-03,True,0.0,0.0,8.333333,0.009564
3,FAM135B,6,5,0.001229,0.001024,1.024534e-06,1.107438e-03,True,0.0,0.0,6.944444,0.008533
4,AGO4,4,4,0.001549,0.001549,2.791318e-05,1.034515e-02,True,0.0,0.0,5.555556,0.008603
5,PRPF6,4,4,0.001417,0.001417,3.933866e-05,1.327831e-02,True,0.0,0.0,5.555556,0.007872

In [4]:
hpv_pos_som_top_direct

,DRUG,NUM_DIRECT_TARGETS_HIT,TOTAL_TARGETS_IN_DRUGBANK,PERCENTAGE_OF_TARGETS_HIT,GENE_TARGET,GENE_Cohort_Frequency,GENE_Normalized_Count,GENE_Normalized_Cohort_Frequency,GENE_SIGNIFICANT,ACTION,SPECIFIC_FUNCTION,drug_hypergeom_p_value,drug_hypergeom_fdr,drug_empirical_p_value,drug_empirical_fdr
0,Buparlisib,1,4,25.0,PIK3CA,17,0.002182,0.002061,True,inhibitor,1-phosphatidylinositol-3-kinase activity,1.072259e-06,0.000193,0.00002,0.002839
1,Copanlisib,1,4,25.0,PIK3CA,17,0.002182,0.002061,True,inhibitor,1-phosphatidylinositol-3-kinase activity,1.072259e-06,0.000193,0.00002,0.002839
2,CH-5132799,1,4,25.0,PIK3CA,17,0.002182,0.002061,True,inhibitor,1-phosphatidylinositol-3-kinase activity,1.072259e-06,0.000193,0.00002,0.002839
3,XL765,1,5,20.0,PIK3CA,17,0.002182,0.002061,True,NaN,1-phosphatidylinositol-3-kinase activity,3.387988e-08,0.000012,0.00001,0.001735
4,Wortmannin,1,5,20.0,PIK3CA,17,0.002182,0.002061,True,NaN,1-phosphatidylinositol-3-kinase activity,5.225777e-06,0.000816,0.00001,0.001735

In [5]:
hpv_pos_som_top_indirect

,DRUG,CONNECTED_TO (risk gene),Number of risk or immediate neighbor genes targeted,total_genes_targeted_in_drugbank,PERCENTAGE_OF_TARGETS_HIT,Number of indirect genes connected to this risk gene,GENE_TARGET,GENE_Cohort_Frequency,GENE_Normalized_Count,GENE_Normalized_Cohort_Frequency,ACTION,SPECIFIC_FUNCTION,drug_hypergeom_fdr,drug_empirical_fdr
0,nintedanib,PIK3CA,12,12,100.000000,12,"FGFR1, FGFR3, SRC, KDR, PDGFRB, LCK, FLT1, PDG...",17,0.002182,0.002061,inhibitor,ATP binding,4.039591e-15,0.001735
1,sorafenib,PIK3CA,11,11,100.000000,11,"RAF1, FGFR1, KDR, PDGFRB, EGFR, FLT1, BRAF, KI...",17,0.002182,0.002061,"inhibitor, antagonist","ATP binding, actin filament binding",6.741882e-14,0.001735
2,erdafitinib,PIK3CA,10,10,100.000000,10,"FGFR1, FGFR4, FGFR3, KDR, PDGFRB, KIT, CSF1R, ...",17,0.002182,0.002061,"inhibitor, substrate",ATP binding,1.275949e-12,0.001735
3,lenvatinib,PIK3CA,10,10,100.000000,10,"FGFR1, FGFR4, FGFR3, KDR, FLT1, KIT, RET, PDGF...",17,0.002182,0.002061,inhibitor,ATP binding,1.275949e-12,0.001735
4,brigatinib,PIK3CA,9,9,100.000000,9,"IGF1R, MET, ALK, ERBB4, INSR, EGFR, ABL1, ERBB...",17,0.002182,0.002061,"inhibitor, binding","ATP binding, amyloid-beta binding, actin filam...",2.935392e-11,0.001735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,tetrabromo-2-benzotriazole,PIK3CA,5,18,27.777778,5,"MAP2K1, LCK, RPS6KB1, AKT1, MAPK1",17,0.002182,0.002061,inhibitor,"ATP binding, 14-3-3 protein binding",2.168119e-02,0.015250
89,quercetin,PIK3CA,6,32,18.750000,5,"HCK, PIK3CG, ESR1, STAT3, HSP90AA1",17,0.002182,0.002061,inhibitor,"ATP binding, 1-phosphatidylinositol-3-kinase a...",4.923945e-02,0.035390
90,fostamatinib,PIK3CA,54,299,18.060201,53,"PRKCD, ROS1, AXL, PDPK1, HCK, CDK4, INSRR, RAF...",17,0.002182,0.002061,inhibitor,"ATP binding, 3-phosphoinositide-dependent prot...",2.364423e-24,0.001735
91,fostamatinib,AGO4,54,299,18.060201,1,ERN1,4,0.001549,0.001549,inhibitor,ADP binding,2.364423e-24,0.001735
92,quercetin,PRPF6,6,32,18.750000,1,SF3B3,4,0.001417,0.001417,NaN,protein-containing complex binding,4.923945e-02,0.035390

### HPV-

In [6]:
hpv_negative_genes

,Gene,Count,Cohort_Frequency,Normalized_Count,Normalized_Cohort_Frequency,P_Value,Adjusted_P_Value,Significant,Empirical_P_Value,Adjusted_Empirical_P_Value,frequency_percentage,mutation_score
0,TP53,405,345,0.014275,0.012160,0.000000e+00,0.000000e+00,True,0.0,0.0,0.438998,0.006267
1,CDKN2A,105,101,0.027668,0.026614,6.503132e-132,4.632181e-128,True,0.0,0.0,0.128518,0.003556
2,FAT1,133,104,0.007515,0.005876,1.187875e-94,5.640822e-91,True,0.0,0.0,0.132336,0.000994
3,PIK3CA,69,67,0.008364,0.008121,5.925466e-53,2.110355e-49,True,0.0,0.0,0.085255,0.000713
4,LRP1B,92,70,0.004749,0.003613,1.484220e-49,4.228839e-46,True,0.0,0.0,0.089072,0.000423
...,...,...,...,...,...,...,...,...,...,...,...,...
161,TEX13A,9,9,0.003667,0.003667,2.545743e-05,1.048169e-03,True,0.0,0.0,0.011452,0.000042
162,OR8J3,8,8,0.004233,0.004233,2.624608e-05,1.065990e-03,True,0.0,0.0,0.010180,0.000043
163,GABRQ,8,8,0.004219,0.004219,2.683466e-05,1.076863e-03,True,0.0,0.0,0.010180,0.000043
164,OR2G6,8,8,0.004219,0.004219,2.683466e-05,1.076863e-03,True,0.0,0.0,0.010180,0.000043
165,FAM83C,8,8,0.003570,0.003570,8.516241e-05,2.726345e-03,True,0.0,0.0,0.010180,0.000036

In [7]:
hpv_neg_som_top_direct

,DRUG,NUM_DIRECT_TARGETS_HIT,TOTAL_TARGETS_IN_DRUGBANK,PERCENTAGE_OF_TARGETS_HIT,GENE_TARGET,GENE_Cohort_Frequency,GENE_Normalized_Count,GENE_Normalized_Cohort_Frequency,GENE_SIGNIFICANT,ACTION,SPECIFIC_FUNCTION,drug_hypergeom_p_value,drug_hypergeom_fdr,drug_empirical_p_value,drug_empirical_fdr
0,3-isobutyl-1-methyl-7H-xanthine,1,15,6.666667,PDE3A,15,0.004674,0.004382,True,inhibitor,"3',5'-cGMP-inhibited cyclic-nucleotide phospho...",2.553685e-04,4.784584e-02,0.00019,0.039553
1,Fludiazepam,1,17,5.882353,GABRG1,11,0.007885,0.007885,True,potentiator,GABA receptor binding,2.556743e-06,1.260609e-03,0.00001,0.003747
2,Ethanol,3,54,5.555556,GRIN3A,12,0.004185,0.003587,True,antagonist,calcium channel activity,3.048945e-07,2.596593e-04,0.00001,0.003747
3,Ethanol,3,54,5.555556,GABRQ,8,0.004219,0.004219,True,NaN,GABA-A receptor activity,3.048945e-07,2.596593e-04,0.00001,0.003747
4,Ethanol,3,54,5.555556,GABRG1,11,0.007885,0.007885,True,NaN,GABA receptor binding,3.048945e-07,2.596593e-04,0.00001,0.003747
5,Regorafenib,1,18,5.555556,EPHA2,20,0.008197,0.006831,True,inhibitor,ATP binding,5.157973e-08,1.044296e-04,0.00001,0.003747
6,Acetylsalicylic acid,1,20,5.000000,TP53,345,0.014275,0.012160,True,inducer,14-3-3 protein binding,6.224881e-07,4.859557e-04,0.00001,0.003747
7,Glutamic acid,3,62,4.838710,GRIN3A,12,0.004185,0.003587,True,NaN,calcium channel activity,5.875108e-11,2.751901e-07,0.00001,0.003747
8,Glutamic acid,3,62,4.838710,GLUD2,9,0.005376,0.005376,True,substrate,ADP binding,5.875108e-11,2.751901e-07,0.00001,0.003747
9,Glutamic acid,3,62,4.838710,ENPEP,12,0.004180,0.004180,True,NaN,aminopeptidase activity,5.875108e-11,2.751901e-07,0.00001,0.003747
10,Dasatinib,1,23,4.347826,EPHA2,20,0.008197,0.006831,True,antagonist,ATP binding,1.350788e-06,7.443634e-04,0.00001,0.003747
11,Fostamatinib,1,300,0.333333,EPHA2,20,0.008197,0.006831,True,inhibitor,ATP binding,2.427756e-12,2.274322e-08,0.00001,0.003747

In [8]:
hpv_neg_som_top_indirect

,DRUG,CONNECTED_TO (risk gene),Number of risk or immediate neighbor genes targeted,total_genes_targeted_in_drugbank,PERCENTAGE_OF_TARGETS_HIT,Number of indirect genes connected to this risk gene,GENE_TARGET,GENE_Cohort_Frequency,GENE_Normalized_Count,GENE_Normalized_Cohort_Frequency,ACTION,SPECIFIC_FUNCTION,drug_hypergeom_fdr,drug_empirical_fdr
0,pp-121,TP53,10,10,100.000000,1,PRKDC,345,0.014275,0.012160,inhibitor,ATP binding,0.000239,0.003747
1,pd-166326,TP53,9,9,100.000000,1,MAPK14,345,0.014275,0.012160,inhibitor,ATP binding,0.000685,0.003747
2,seliciclib,TP53,7,7,100.000000,6,"CDK7, CSNK1E, CDK9, MAPK3, CDK1, CDK2",345,0.014275,0.012160,inhibitor,"ATP binding, 7SK snRNA binding",0.008197,0.009691
3,amuvatinib,TP53,6,6,100.000000,1,RAD51,345,0.014275,0.012160,NaN,ATP binding,0.028340,0.033063
4,trilaciclib,TP53,6,6,100.000000,5,"CDK7, CDK6, CDK9, CDK5, CDK2",345,0.014275,0.012160,inhibitor,"ATP binding, 7SK snRNA binding, acetylcholine ...",0.028340,0.036030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,resveratrol,COL1A2,16,26,61.538462,2,"ITGB3, ITGA5",17,0.004148,0.004148,NaN,"cell adhesion molecule binding, calcium ion bi...",0.005552,0.003747
142,artenimol,COL1A2,39,104,37.500000,1,TAGLN,17,0.004148,0.004148,ligand,actin binding,0.014303,0.012491
143,artenimol,MYH8,39,104,37.500000,1,TPM1,24,0.004130,0.004130,ligand,actin binding,0.014303,0.012491
144,3-isobutyl-1-methyl-7h-xanthine,IMPG2,10,15,66.666667,1,PDE6G,15,0.004029,0.004029,NaN,"calmodulin-activated 3',5'-cyclic-GMP phosphod...",0.047846,0.039553
145,heparin,F13B,9,12,75.000000,2,"F10, SERPINC1",10,0.003675,0.003675,"inhibitor, potentiator","calcium ion binding, heparin binding",0.030578,0.038323