In [28]:
import pandas as pd
import os
from tqdm import tqdm
import matplotlib.pyplot as plt
import plotly.express as px

### Data

In [29]:
### CNV data
hpv_pos_amp_top_drugBank_drug_candidates = pd.read_csv('Results/hpv_pos_amp_top_drugBank_drug_candidates.csv')
hpv_pos_del_top_drugBank_drug_candidates = pd.read_csv('Results/hpv_pos_del_top_drugBank_drug_candidates.csv')

hpv_neg_amp_top_drugBank_drug_candidates = pd.read_csv('Results/hpv_neg_amp_top_drugBank_drug_candidates.csv')
hpv_neg_del_top_drugBank_drug_candidates = pd.read_csv('Results/hpv_neg_del_top_drugBank_drug_candidates.csv')

In [30]:
### som data
hpv_pos_som_top_drugBank_drug_candidates = pd.read_csv('Results/hpv_pos_som_top_drugBank_drug_candidates.csv')
hpv_neg_som_top_drugBank_drug_candidates = pd.read_csv('Results/hpv_neg_som_top_drugBank_drug_candidates.csv')

### Compare results

#### HPV+

In [31]:
### Venn diagram for hpv pos genes
print(f'Number of genes in HPV positive amplification genes: {hpv_pos_amp_top_drugBank_drug_candidates['GENE_TARGET'].nunique()}')
print(f'overlap between hpv positive amplification and deletion: {len(set(hpv_pos_amp_top_drugBank_drug_candidates["GENE_TARGET"]).intersection(set(hpv_pos_del_top_drugBank_drug_candidates["GENE_TARGET"])))}')
print(f'Number of genes in HPV positive deletion genes: {hpv_pos_del_top_drugBank_drug_candidates['GENE_TARGET'].nunique()}')

print(f'Number of genes in hpv positive somatic genes: {hpv_pos_som_top_drugBank_drug_candidates['GENE_TARGET'].nunique()}')
print(f'overlap between hpv positive somatic and amplification: {len(set(hpv_pos_som_top_drugBank_drug_candidates["GENE_TARGET"]).intersection(set(hpv_pos_amp_top_drugBank_drug_candidates["GENE_TARGET"])))}')
print(f'overlap between hpv positive somatic and deletion: {len(set(hpv_pos_som_top_drugBank_drug_candidates["GENE_TARGET"]).intersection(set(hpv_pos_del_top_drugBank_drug_candidates["GENE_TARGET"])))}')

print(f'Overlap between hpv positive amplification and deletion and somatic: {len(set(hpv_pos_amp_top_drugBank_drug_candidates["GENE_TARGET"]).intersection(set(hpv_pos_som_top_drugBank_drug_candidates["GENE_TARGET"])).intersection(set(hpv_pos_del_top_drugBank_drug_candidates["GENE_TARGET"])))}')

Number of genes in HPV positive amplification genes: 353
overlap between hpv positive amplification and deletion: 63
Number of genes in HPV positive deletion genes: 102
Number of genes in hpv positive somatic genes: 77
overlap between hpv positive somatic and amplification: 67
overlap between hpv positive somatic and deletion: 23
Overlap between hpv positive amplification and deletion and somatic: 23

In [32]:
### Venn diagram for hpv pos drugs

print(f'Number of drugs in HPV positive amplification drugs: {hpv_pos_amp_top_drugBank_drug_candidates['DRUG'].nunique()}')
print(f'overlap between hpv positive amplification and deletion: {len(set(hpv_pos_amp_top_drugBank_drug_candidates["DRUG"]).intersection(set(hpv_pos_del_top_drugBank_drug_candidates["DRUG"])))}')
### those in hpv pos del not in amp
print('Number of Drugs in hpv pos del not in amp:')
print(len(set(hpv_pos_del_top_drugBank_drug_candidates['DRUG']) - set(hpv_pos_amp_top_drugBank_drug_candidates['DRUG'])))
### those in hpv pos amp not in del
print('Number of Drugs in hpv pos amp not in del:')
print(len(set(hpv_pos_amp_top_drugBank_drug_candidates['DRUG']) - set(hpv_pos_del_top_drugBank_drug_candidates['DRUG'])))


print(f'Number of drugs in HPV positive deletion drugs: {hpv_pos_del_top_drugBank_drug_candidates['DRUG'].nunique()}')

print(f'Number of drugs in hpv positive somatic drugs: {hpv_pos_som_top_drugBank_drug_candidates['DRUG'].nunique()}')
### only in som not in amp or del
print('Number of Drugs in hpv pos som not in amp or del:')
print(len(set(hpv_pos_som_top_drugBank_drug_candidates['DRUG']) - set(hpv_pos_amp_top_drugBank_drug_candidates['DRUG']) - set(hpv_pos_del_top_drugBank_drug_candidates['DRUG'])))
print(f'overlap between hpv positive somatic and amplification: {len(set(hpv_pos_som_top_drugBank_drug_candidates["DRUG"]).intersection(set(hpv_pos_amp_top_drugBank_drug_candidates["DRUG"])))}')
print(f'overlap between hpv positive somatic and deletion: {len(set(hpv_pos_som_top_drugBank_drug_candidates["DRUG"]).intersection(set(hpv_pos_del_top_drugBank_drug_candidates["DRUG"])))}')

print(f'Overlap between hpv positive amplification and deletion and somatic: {len(set(hpv_pos_amp_top_drugBank_drug_candidates["DRUG"]).intersection(set(hpv_pos_som_top_drugBank_drug_candidates["DRUG"])).intersection(set(hpv_pos_del_top_drugBank_drug_candidates["DRUG"])))}')

Number of drugs in HPV positive amplification drugs: 143
overlap between hpv positive amplification and deletion: 32
Number of Drugs in hpv pos del not in amp:
10
Number of Drugs in hpv pos amp not in del:
111
Number of drugs in HPV positive deletion drugs: 42
Number of drugs in hpv positive somatic drugs: 90
Number of Drugs in hpv pos som not in amp or del:
34
overlap between hpv positive somatic and amplification: 56
overlap between hpv positive somatic and deletion: 27
Overlap between hpv positive amplification and deletion and somatic: 27

In [33]:
hpv_pos_amp_top_drugBank_drug_candidates

,GENE_TARGET,CONNECTED_TO,PPI_SCORE,DRUG,GENE_GISTIC,GENE_normalized_gistic_score,GENE_frequency_percentage,GENE_SIGNIFICANT,ACTION,SPECIFIC_FUNCTION,drug_hypergeom_p_value,drug_hypergeom_fdr,drug_empirical_p_value,drug_empirical_fdr,HNC_approved_medication,DIRECT
0,KNG1,HRG,972,Zinc,0.302421,0.242965,33.484163,True,NaN,cysteine-type endopeptidase inhibitor activity,2.168867e-13,4.063589e-10,0.00001,0.002285,False,0
1,KNG1,HRG,972,Copper,0.302421,0.242965,33.484163,True,NaN,cysteine-type endopeptidase inhibitor activity,8.218045e-15,2.566222e-11,0.00001,0.002285,False,0
2,KNG1,HRG,972,Zinc acetate,0.302421,0.242965,33.484163,True,NaN,cysteine-type endopeptidase inhibitor activity,2.168867e-13,4.063589e-10,0.00001,0.002285,False,0
3,KNG1,HRG,972,Zinc chloride,0.302421,0.242965,33.484163,True,cofactor,cysteine-type endopeptidase inhibitor activity,4.050306e-15,1.897163e-11,0.00001,0.002285,False,0
4,KNG1,HRG,972,"Zinc sulfate, unspecified form",0.302421,0.242965,33.484163,True,cofactor,cysteine-type endopeptidase inhibitor activity,4.050306e-15,1.897163e-11,0.00001,0.002285,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1869,AHSG,NaN,0,Zinc,0.302421,0.242965,33.484163,True,NaN,cysteine-type endopeptidase inhibitor activity,2.168867e-13,4.063589e-10,0.00001,0.002285,False,17
1870,AHSG,NaN,0,Copper,0.302421,0.242965,33.484163,True,NaN,cysteine-type endopeptidase inhibitor activity,8.218045e-15,2.566222e-11,0.00001,0.002285,False,17
1871,AHSG,NaN,0,Zinc acetate,0.302421,0.242965,33.484163,True,NaN,cysteine-type endopeptidase inhibitor activity,2.168867e-13,4.063589e-10,0.00001,0.002285,False,17
1872,AHSG,NaN,0,Zinc chloride,0.302421,0.242965,33.484163,True,chelator,cysteine-type endopeptidase inhibitor activity,4.050306e-15,1.897163e-11,0.00001,0.002285,False,17
1873,AHSG,NaN,0,"Zinc sulfate, unspecified form",0.302421,0.242965,33.484163,True,chelator,cysteine-type endopeptidase inhibitor activity,4.050306e-15,1.897163e-11,0.00001,0.002285,False,17

In [34]:
hpv_pos_del_top_drugBank_drug_candidates

,GENE_TARGET,CONNECTED_TO,PPI_SCORE,DRUG,GENE_GISTIC,GENE_normalized_gistic_score,GENE_frequency_percentage,GENE_SIGNIFICANT,ACTION,SPECIFIC_FUNCTION,drug_hypergeom_p_value,drug_hypergeom_fdr,drug_empirical_p_value,drug_empirical_fdr,HNC_approved_medication,DIRECT
0,HDAC2,SCML2,908,Vorinostat,0.091071,0.0,14.479638,True,inhibitor,chromatin binding,8.755887e-05,0.029295,0.00010,0.032119,False,0
1,HDAC2,SCML2,908,Pracinostat,0.091071,0.0,14.479638,True,NaN,chromatin binding,1.466201e-04,0.032703,0.00013,0.033829,False,0
2,HDAC2,SCML2,908,Martinostat,0.091071,0.0,14.479638,True,inhibitor,chromatin binding,5.640764e-06,0.002642,0.00004,0.016292,False,0
3,RPL14,EIF2S3,835,Artenimol,0.091071,0.0,14.479638,True,ligand,cadherin binding,4.577312e-07,0.000306,0.00001,0.004930,False,0
4,RPL3,EIF2S3,898,(S)-3-phenyllactic acid,0.091071,0.0,14.479638,True,NaN,RNA binding,4.394774e-07,0.000306,0.00001,0.004930,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441,HDAC3,TBL1X,999,Pracinostat,0.091071,0.0,14.479638,True,NaN,chromatin binding,1.466201e-04,0.032703,0.00013,0.033829,False,0
442,HDAC3,TBL1X,999,Martinostat,0.091071,0.0,14.479638,True,inhibitor,chromatin binding,5.640764e-06,0.002642,0.00004,0.016292,False,0
443,TLR7,NaN,0,Golotimod,0.091071,0.0,14.479638,True,NaN,double-stranded RNA binding,1.605536e-05,0.006539,0.00003,0.012774,False,3
444,POLA1,NaN,0,Cladribine,0.091071,0.0,14.479638,True,inhibitor,chromatin binding,9.203648e-05,0.029731,0.00011,0.032119,False,3
445,VEGFD,NaN,0,TG-100801,0.091071,0.0,14.479638,True,inhibitor,chemoattractant activity,4.038151e-05,0.015762,0.00008,0.031226,False,3

In [35]:
### show drugs of overlap
hpv_pos_drug_overlap = set(hpv_pos_amp_top_drugBank_drug_candidates["DRUG"]).intersection(
	set(hpv_pos_som_top_drugBank_drug_candidates["DRUG"])
).intersection(set(hpv_pos_del_top_drugBank_drug_candidates["DRUG"]))

top_hpv_pos_overlap_drug = hpv_pos_amp_top_drugBank_drug_candidates[
	hpv_pos_amp_top_drugBank_drug_candidates["DRUG"].isin(hpv_pos_drug_overlap)
]
top_hpv_pos_overlap_drug.drop_duplicates(subset=('DRUG', 'GENE_TARGET'), inplace=True)
top_hpv_pos_overlap_drug

/var/folders/5p/swntgnbj3fbfxkx02kt3fq980000gn/T/ipykernel_40477/3204924084.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_hpv_pos_overlap_drug.drop_duplicates(subset=('DRUG', 'GENE_TARGET'), inplace=True)

,GENE_TARGET,CONNECTED_TO,PPI_SCORE,DRUG,GENE_GISTIC,GENE_normalized_gistic_score,GENE_frequency_percentage,GENE_SIGNIFICANT,ACTION,SPECIFIC_FUNCTION,drug_hypergeom_p_value,drug_hypergeom_fdr,drug_empirical_p_value,drug_empirical_fdr,HNC_approved_medication,DIRECT
160,MAPK11,GNB4,737,Regorafenib,0.302084,0.227500,33.484163,True,inhibitor,ATP binding,2.203707e-10,2.949189e-07,0.00001,0.002285,False,0
221,MAPK14,GNB4,738,PD-166326,0.302084,0.227500,33.484163,True,inhibitor,ATP binding,3.905673e-08,1.590798e-05,0.00001,0.002285,False,0
432,IGF1R,PIK3CA,978,Brigatinib,0.302482,0.245792,33.484163,True,inhibitor,ATP binding,3.905673e-08,1.590798e-05,0.00001,0.002285,False,0
445,RAF1,PIK3CA,972,Sorafenib,0.302482,0.245792,33.484163,True,inhibitor,ATP binding,8.686883e-10,1.017234e-06,0.00001,0.002285,False,0
446,RAF1,PIK3CA,972,Regorafenib,0.302482,0.245792,33.484163,True,inhibitor,ATP binding,2.203707e-10,2.949189e-07,0.00001,0.002285,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
842,FLT3,PIK3CA,958,Brigatinib,0.302482,0.245792,33.484163,True,inhibitor,ATP binding,3.905673e-08,1.590798e-05,0.00001,0.002285,False,0
843,FLT3,PIK3CA,958,Amuvatinib,0.302482,0.245792,33.484163,True,NaN,ATP binding,1.165378e-05,2.228012e-03,0.00001,0.002285,False,0
844,FLT3,PIK3CA,958,Pexidartinib,0.302482,0.245792,33.484163,True,inhibitor,ATP binding,5.168234e-04,3.433760e-02,0.00051,0.038913,False,0
1167,EPHA2,CLDN1,704,Regorafenib,0.297817,0.031631,33.031674,True,inhibitor,ATP binding,2.203707e-10,2.949189e-07,0.00001,0.002285,False,0
1300,RAD51,RFC4,888,Amuvatinib,0.302421,0.242965,33.484163,True,NaN,ATP binding,1.165378e-05,2.228012e-03,0.00001,0.002285,False,0

In [36]:
hpv_pos_drug_overlap

{'Amuvatinib',
 'BMS-690514',
 'Brigatinib',
 'Erdafitinib',
 'Famitinib',
 'Futibatinib',
 'Infigratinib',
 'Lenvatinib',
 'Linifanib',
 'Lucitanib',
 'Nintedanib',
 'PD-166326',
 'Pazopanib',
 'Pemigatinib',
 'Pexidartinib',
 'Ponatinib',
 'Regorafenib',
 'Ripretinib',
 'Selpercatinib',
 'Semaxanib',
 'Sorafenib',
 'Sunitinib',
 'Surufatinib',
 'Tivozanib',
 'Vatalanib',
 'XL820',
 'XL999'}

#### HPV-

In [37]:
### Venn diagram for hpv neg genes
print(f'Number of genes in HPV negative amplification genes: {hpv_neg_amp_top_drugBank_drug_candidates['GENE_TARGET'].nunique()}')
print(f'overlap between hpv negative amplification and deletion: {len(set(hpv_neg_amp_top_drugBank_drug_candidates["GENE_TARGET"]).intersection(set(hpv_neg_del_top_drugBank_drug_candidates["GENE_TARGET"])))}')
print(f'Number of genes in HPV negative deletion genes: {hpv_neg_del_top_drugBank_drug_candidates['GENE_TARGET'].nunique()}')

print(f'Number of genes in hpv negative somatic genes: {hpv_neg_som_top_drugBank_drug_candidates['GENE_TARGET'].nunique()}')
print(f'overlap between hpv negative somatic and amplification: {len(set(hpv_neg_som_top_drugBank_drug_candidates["GENE_TARGET"]).intersection(set(hpv_neg_amp_top_drugBank_drug_candidates["GENE_TARGET"])))}')
print(f'overlap between hpv negative somatic and deletion: {len(set(hpv_neg_som_top_drugBank_drug_candidates["GENE_TARGET"]).intersection(set(hpv_neg_del_top_drugBank_drug_candidates["GENE_TARGET"])))}')

print(f'Overlap between hpv negative amplification and deletion and somatic: {len(set(hpv_neg_amp_top_drugBank_drug_candidates["GENE_TARGET"]).intersection(set(hpv_neg_som_top_drugBank_drug_candidates["GENE_TARGET"])).intersection(set(hpv_neg_del_top_drugBank_drug_candidates["GENE_TARGET"])))}')

Number of genes in HPV negative amplification genes: 437
overlap between hpv negative amplification and deletion: 52
Number of genes in HPV negative deletion genes: 68
Number of genes in hpv negative somatic genes: 307
overlap between hpv negative somatic and amplification: 122
overlap between hpv negative somatic and deletion: 32
Overlap between hpv negative amplification and deletion and somatic: 26

In [38]:
### Venn diagram for hpv neg drugs
print(f'Number of drugs in HPV negative amplification drugs: {hpv_neg_amp_top_drugBank_drug_candidates['DRUG'].nunique()}')
print(f'overlap between hpv negative amplification and deletion: {len(set(hpv_neg_amp_top_drugBank_drug_candidates["DRUG"]).intersection(set(hpv_neg_del_top_drugBank_drug_candidates["DRUG"])))}')
print(f'Number of drugs in HPV negative deletion drugs: {hpv_neg_del_top_drugBank_drug_candidates['DRUG'].nunique()}')

print(f'Number of drugs in hpv negative somatic drugs: {hpv_neg_som_top_drugBank_drug_candidates['DRUG'].nunique()}')
print(f'overlap between hpv negative somatic and amplification: {len(set(hpv_neg_som_top_drugBank_drug_candidates["DRUG"]).intersection(set(hpv_neg_amp_top_drugBank_drug_candidates["DRUG"])))}')
print(f'overlap between hpv negative somatic and deletion: {len(set(hpv_neg_som_top_drugBank_drug_candidates["DRUG"]).intersection(set(hpv_neg_del_top_drugBank_drug_candidates["DRUG"])))}')

print(f'Overlap between hpv negative amplification and deletion and somatic: {len(set(hpv_neg_amp_top_drugBank_drug_candidates["DRUG"]).intersection(set(hpv_neg_som_top_drugBank_drug_candidates["DRUG"])).intersection(set(hpv_neg_del_top_drugBank_drug_candidates["DRUG"])))}')

Number of drugs in HPV negative amplification drugs: 90
overlap between hpv negative amplification and deletion: 12
Number of drugs in HPV negative deletion drugs: 31
Number of drugs in hpv negative somatic drugs: 42
overlap between hpv negative somatic and amplification: 27
overlap between hpv negative somatic and deletion: 11
Overlap between hpv negative amplification and deletion and somatic: 9

In [39]:
### hpv negative top overlap drughs
hpv_neg_drug_overlap = set(hpv_neg_amp_top_drugBank_drug_candidates["DRUG"]).intersection(
    set(hpv_neg_som_top_drugBank_drug_candidates["DRUG"])
).intersection(set(hpv_neg_del_top_drugBank_drug_candidates["DRUG"]))
hpv_neg_drug_overlap

{'Artenimol',
 'Bisindolylmaleimide I',
 'Brigatinib',
 'CI-1040',
 'Enzastaurin',
 'PD-166326',
 'PP-121',
 'Ponatinib',
 'Tetrabromo-2-Benzotriazole'}

In [40]:
### combine top candidate information from sources
hpv_neg_top_drug_candidate_information = pd.concat(
    [hpv_neg_amp_top_drugBank_drug_candidates, hpv_neg_del_top_drugBank_drug_candidates, hpv_neg_som_top_drugBank_drug_candidates],
    ignore_index=True
)
hpv_neg_top_drug_candidate_information = hpv_neg_top_drug_candidate_information[hpv_neg_top_drug_candidate_information['DRUG'].isin(hpv_neg_drug_overlap)]
hpv_neg_top_drug_candidate_information['CONNECTED_TO'].fillna('', inplace=True)
### aggregate this to show how many genes each drug targets
agg_hpv_neg_drug_candidate_information = hpv_neg_top_drug_candidate_information.groupby('DRUG').agg({
    'GENE_TARGET': lambda x: ', '.join(set(x)),
    'CONNECTED_TO': lambda x: ','.join(set(x)),
    'drug_hypergeom_fdr': 'min',
    'drug_empirical_fdr': 'min',
}).reset_index()

agg_hpv_neg_drug_candidate_information['num_targeted_genes'] = agg_hpv_neg_drug_candidate_information['GENE_TARGET'].apply(lambda x: len(x.split(', ')))
agg_hpv_neg_drug_candidate_information['num_connected_to'] = agg_hpv_neg_drug_candidate_information['CONNECTED_TO'].apply(lambda x: len(set(x.split(','))))
agg_hpv_neg_drug_candidate_information = agg_hpv_neg_drug_candidate_information.sort_values(by=['drug_hypergeom_fdr', 'drug_empirical_fdr'], ascending=[True, True]).reset_index(drop=True)
agg_hpv_neg_drug_candidate_information

/var/folders/5p/swntgnbj3fbfxkx02kt3fq980000gn/T/ipykernel_40477/3021201030.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  hpv_neg_top_drug_candidate_information['CONNECTED_TO'].fillna('', inplace=True)

,DRUG,GENE_TARGET,CONNECTED_TO,drug_hypergeom_fdr,drug_empirical_fdr,num_targeted_genes,num_connected_to
0,Artenimol,"HNRNPA2B1, RPS6, RPS28, VIM, TPI1, PKM, IQGAP1...","IGF2BP2,MFN1,MYH8,RAC1,P3H2,POLR2H,RPS4Y2,TKTL...",4.169813e-07,0.005511,66,46
1,Bisindolylmaleimide I,"PRKCI, CHEK1, MAPK14, GSK3B, MAPK1, MAPK11, PR...","PRKCI,ECT2,,MRPL47,TP53,PIK3CA,RFC4,ADCY2,EIF2...",2.371705e-06,0.002755,15,15
2,Ponatinib,"KDR, LYN, SRC, FGFR3, RET, PDGFRA, TEK, FGFR1,...","FGF12,EPHB3,PIK3CA,IL1RAP,THPO,KNG1,CDKN2A",4.725309e-06,0.002755,14,7
3,CI-1040,"CHEK1, MAP3K1, MAPK14, GSK3B, MAPK1, MAPK11, R...","TP53,MRPL47,PIK3CA,EIF4A2,RFC4,ADCY2,EIF2B5,GN...",1.747181e-04,0.005511,12,15
4,PP-121,"KDR, SRC, PDGFRA, PRKDC, EGFR, PIK3CG, ABL1, H...","PRKCI,AP2M1,IGF2BP2,TP53,EPHB3,PIK3CA,THPO,KNG...",2.393902e-04,0.009758,10,11
5,PD-166326,"PDGFRB, MAPK14, SRC, PDGFRA, FGFR1, EGFR, ABL1...","AP2M1,IGF2BP2,TP53,FGF12,EPHB3,PIK3CA,IL1RAP,T...",3.215223e-04,0.002755,9,12
6,Brigatinib,"IGF1R, ERBB2, ERBB4, FLT3, INSR, MET, EGFR, AB...","AP2M1,IGF2BP2,EPHB3,PIK3CA,THPO,SLC2A2,SOX2,CD...",3.215223e-04,0.004804,9,8
7,Tetrabromo-2-Benzotriazole,"CHEK1, MAPK14, GSK3B, MAPK1, MAPK11, RPS6KB1, ...","TP53,MRPL47,PIK3CA,EIF4A2,RFC4,ADCY2,EIF2B5,GN...",5.129948e-04,0.002755,14,15
8,Enzastaurin,"CHEK1, PRKCB, AURKB, AKT1, PIK3CG, AURKA, PIK3...","PRKCI,ECT2,TP53,PIK3CA,RFC4,GNB4,ADIPOQ,AJUBA,...",1.659620e-03,0.004804,8,11

In [41]:
agg_hpv_neg_drug_candidate_information

,DRUG,GENE_TARGET,CONNECTED_TO,drug_hypergeom_fdr,drug_empirical_fdr,num_targeted_genes,num_connected_to
0,Artenimol,"HNRNPA2B1, RPS6, RPS28, VIM, TPI1, PKM, IQGAP1...","IGF2BP2,MFN1,MYH8,RAC1,P3H2,POLR2H,RPS4Y2,TKTL...",4.169813e-07,0.005511,66,46
1,Bisindolylmaleimide I,"PRKCI, CHEK1, MAPK14, GSK3B, MAPK1, MAPK11, PR...","PRKCI,ECT2,,MRPL47,TP53,PIK3CA,RFC4,ADCY2,EIF2...",2.371705e-06,0.002755,15,15
2,Ponatinib,"KDR, LYN, SRC, FGFR3, RET, PDGFRA, TEK, FGFR1,...","FGF12,EPHB3,PIK3CA,IL1RAP,THPO,KNG1,CDKN2A",4.725309e-06,0.002755,14,7
3,CI-1040,"CHEK1, MAP3K1, MAPK14, GSK3B, MAPK1, MAPK11, R...","TP53,MRPL47,PIK3CA,EIF4A2,RFC4,ADCY2,EIF2B5,GN...",1.747181e-04,0.005511,12,15
4,PP-121,"KDR, SRC, PDGFRA, PRKDC, EGFR, PIK3CG, ABL1, H...","PRKCI,AP2M1,IGF2BP2,TP53,EPHB3,PIK3CA,THPO,KNG...",2.393902e-04,0.009758,10,11
5,PD-166326,"PDGFRB, MAPK14, SRC, PDGFRA, FGFR1, EGFR, ABL1...","AP2M1,IGF2BP2,TP53,FGF12,EPHB3,PIK3CA,IL1RAP,T...",3.215223e-04,0.002755,9,12
6,Brigatinib,"IGF1R, ERBB2, ERBB4, FLT3, INSR, MET, EGFR, AB...","AP2M1,IGF2BP2,EPHB3,PIK3CA,THPO,SLC2A2,SOX2,CD...",3.215223e-04,0.004804,9,8
7,Tetrabromo-2-Benzotriazole,"CHEK1, MAPK14, GSK3B, MAPK1, MAPK11, RPS6KB1, ...","TP53,MRPL47,PIK3CA,EIF4A2,RFC4,ADCY2,EIF2B5,GN...",5.129948e-04,0.002755,14,15
8,Enzastaurin,"CHEK1, PRKCB, AURKB, AKT1, PIK3CG, AURKA, PIK3...","PRKCI,ECT2,TP53,PIK3CA,RFC4,GNB4,ADIPOQ,AJUBA,...",1.659620e-03,0.004804,8,11